on:
  push:
    branches:
      - master
      - release/*
  pull_request:

name: Run Tests

jobs:

  test:
    name: Tests
    strategy:
        matrix:
          node: [10, 12]
          os: [windows-2016, ubuntu-16.04, ubuntu-18.04, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - run: yarn

      - run: yarn test

  prebuild:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest
        node_version:
          - 14
        node_arch:
          - x64
        include:
          - os: windows-latest
            node_version: 14
            node_arch: x86
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.node_arch }}

      - name: Install Dependencies and Build
        run: yarn

      - name: Prebuild
        run: yarn run prebuild
        env:
          ARCH: ${{ matrix.node_arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./prebuilds
